
	$("#doc1s").hide();
	$("#doc2s").hide();
	$("#doc3s").hide();
	$("#doc4s").hide();
	$("#doc5s").hide();
	$("#doc6s").hide();
	$("#doc7s").hide();
	$("#doc8s").hide();
	$("#doc9s").hide();
	$("#doc10s").hide();
	$("#doc11s").hide();
	$("#doc12s").hide();
	$("#doc13s").hide();
	function myFunction() {
	var x = document.getElementById("cotizacións");

	
	if (cotizacións.value==1){
		document.getElementById("after").innerHTML ="Ver ejemplo 1";
		$("#doc1s").slideDown(2000);
		$("#doc2s").hide();
		$("#doc3s").hide();
		$("#doc4s").hide();
		$("#doc5s").hide();
		$("#doc6s").hide();
		$("#doc7s").hide();
		$("#doc8s").hide();
		$("#doc9s").hide();
		$("#doc10s").hide();
		$("#doc11s").hide();
		$("#doc12s").hide();
		$("#doc13s").hide();
		document.getElementById("after0").innerHTML ="";
		document.getElementById("after2").innerHTML ="";
		document.getElementById("after3").innerHTML ="";
		document.getElementById("after4").innerHTML ="";
		document.getElementById("after5").innerHTML ="";
		document.getElementById("after6").innerHTML ="";
		document.getElementById("after7").innerHTML ="";
		document.getElementById("after8").innerHTML ="";
		document.getElementById("after9").innerHTML ="";
		document.getElementById("after10").innerHTML ="";
		document.getElementById("after11").innerHTML ="";
		document.getElementById("after12").innerHTML ="";
		document.getElementById("after13").innerHTML ="";
	} else if (cotizacións.value==2){
		document.getElementById("after2").innerHTML ="Ver ejemplo 2";
		$("#doc2s").slideDown(2000);
		$("#doc1s").hide();
		$("#doc3s").hide();
		$("#doc4s").hide();
		$("#doc5s").hide();
		$("#doc6s").hide();
		$("#doc7s").hide();
		$("#doc8s").hide();
		$("#doc9s").hide();
		$("#doc10s").hide();
		$("#doc11s").hide();
		$("#doc12s").hide();
		$("#doc13s").hide();
		document.getElementById("after0").innerHTML ="";
		document.getElementById("after").innerHTML ="";
		document.getElementById("after3").innerHTML ="";
		document.getElementById("after4").innerHTML ="";
		document.getElementById("after5").innerHTML ="";
		document.getElementById("after6").innerHTML ="";
		document.getElementById("after7").innerHTML ="";
		document.getElementById("after8").innerHTML ="";
		document.getElementById("after9").innerHTML ="";
		document.getElementById("after10").innerHTML ="";
		document.getElementById("after11").innerHTML ="";
		document.getElementById("after12").innerHTML ="";
		document.getElementById("after13").innerHTML ="";
	} else if (cotizacións.value==3){
		document.getElementById("after3").innerHTML ="Ver ejemplo 3";
		$("#doc3s").slideDown(2000);
		$("#doc1s").hide();
		$("#doc2s").hide();
		$("#doc4s").hide();
		$("#doc5s").hide();
		$("#doc6s").hide();
		$("#doc7s").hide();
		$("#doc8s").hide();
		$("#doc9s").hide();
		$("#doc10s").hide();
		$("#doc11s").hide();
		$("#doc12s").hide();
		$("#doc13s").hide();
		document.getElementById("after0").innerHTML ="";
		document.getElementById("after").innerHTML ="";
		document.getElementById("after2").innerHTML ="";
		document.getElementById("after4").innerHTML ="";
		document.getElementById("after5").innerHTML ="";
		document.getElementById("after6").innerHTML ="";
		document.getElementById("after7").innerHTML ="";
		document.getElementById("after8").innerHTML ="";
		document.getElementById("after9").innerHTML ="";
		document.getElementById("after10").innerHTML ="";
		document.getElementById("after11").innerHTML ="";
		document.getElementById("after12").innerHTML ="";
		document.getElementById("after13").innerHTML ="";
	}else if (cotizacións.value==4){
		document.getElementById("after4").innerHTML ="Ver ejemplo 4";
		$("#doc4s").slideDown(2000);
		$("#doc1s").hide();
		$("#doc2s").hide();
		$("#doc3s").hide();
		$("#doc5s").hide();
		$("#doc6s").hide();
		$("#doc7s").hide();
		$("#doc8s").hide();
		$("#doc9s").hide();
		$("#doc10s").hide();
		$("#doc11s").hide();
		$("#doc12s").hide();
		$("#doc13s").hide();
		document.getElementById("after0").innerHTML ="";
		document.getElementById("after").innerHTML ="";
		document.getElementById("after2").innerHTML ="";
		document.getElementById("after3").innerHTML ="";
		document.getElementById("after5").innerHTML ="";
		document.getElementById("after6").innerHTML ="";
		document.getElementById("after7").innerHTML ="";
		document.getElementById("after8").innerHTML ="";
		document.getElementById("after9").innerHTML ="";
		document.getElementById("after10").innerHTML ="";
		document.getElementById("after11").innerHTML ="";
		document.getElementById("after12").innerHTML ="";
		document.getElementById("after13").innerHTML ="";
	}else if (cotizacións.value==5){
		document.getElementById("after5").innerHTML ="Ver ejemplo 5";
		$("#doc5s").slideDown(2000);
		$("#doc1s").hide();
		$("#doc2s").hide();
		$("#doc3s").hide();
		$("#doc4s").hide();
		$("#doc6s").hide();
		$("#doc7s").hide();
		$("#doc8s").hide();
		$("#doc9s").hide();
		$("#doc10s").hide();
		$("#doc11s").hide();
		$("#doc12s").hide();
		$("#doc13s").hide();
		document.getElementById("after0").innerHTML ="";
		document.getElementById("after").innerHTML ="";
		document.getElementById("after2").innerHTML ="";
		document.getElementById("after3").innerHTML ="";
		document.getElementById("after4").innerHTML ="";
		document.getElementById("after5").innerHTML ="";
		document.getElementById("after6").innerHTML ="";
		document.getElementById("after7").innerHTML ="";
		document.getElementById("after8").innerHTML ="";
		document.getElementById("after9").innerHTML ="";
		document.getElementById("after10").innerHTML ="";
		document.getElementById("after11").innerHTML ="";
		document.getElementById("after12").innerHTML ="";
		document.getElementById("after13").innerHTML ="";
	}else if (cotizacións.value==6){
		document.getElementById("after6").innerHTML ="Ver ejemplo 6";
		$("#doc6s").slideDown(2000);
		$("#doc1s").hide();
		$("#doc2s").hide();
		$("#doc3s").hide();
		$("#doc4s").hide();
		$("#doc5s").hide();
		$("#doc7s").hide();
		$("#doc8s").hide();
		$("#doc9s").hide();
		$("#doc10s").hide();
		$("#doc11s").hide();
		$("#doc12s").hide();
		$("#doc13s").hide();
		document.getElementById("after0").innerHTML ="";
		document.getElementById("after").innerHTML ="";
		document.getElementById("after2").innerHTML ="";
		document.getElementById("after3").innerHTML ="";
		document.getElementById("after4").innerHTML ="";
		document.getElementById("after5").innerHTML ="";
		document.getElementById("after7").innerHTML ="";
		document.getElementById("after8").innerHTML ="";
		document.getElementById("after9").innerHTML ="";
		document.getElementById("after10").innerHTML ="";
		document.getElementById("after11").innerHTML ="";
		document.getElementById("after12").innerHTML ="";
		document.getElementById("after13").innerHTML ="";
	}else if (cotizacións.value==7){
		document.getElementById("after7").innerHTML ="Ver ejemplo 7";
		$("#doc7s").slideDown(2000);
		$("#doc1s").hide();
		$("#doc2s").hide();
		$("#doc3s").hide();
		$("#doc4s").hide();
		$("#doc5s").hide();
		$("#doc6s").hide();
		$("#doc8s").hide();
		$("#doc9s").hide();
		$("#doc10s").hide();
		$("#doc11s").hide();
		$("#doc12s").hide();
		$("#doc13s").hide();
		document.getElementById("after0").innerHTML ="";
		document.getElementById("after").innerHTML ="";
		document.getElementById("after2").innerHTML ="";
		document.getElementById("after3").innerHTML ="";
		document.getElementById("after4").innerHTML ="";
		document.getElementById("after5").innerHTML ="";
		document.getElementById("after6").innerHTML ="";
		document.getElementById("after8").innerHTML ="";
		document.getElementById("after9").innerHTML ="";
		document.getElementById("after10").innerHTML ="";
		document.getElementById("after11").innerHTML ="";
		document.getElementById("after12").innerHTML ="";
		document.getElementById("after13").innerHTML ="";
		
	}else if (cotizacións.value==8){
		document.getElementById("after8").innerHTML ="Ver ejemplo 8";
		$("#doc8s").slideDown(2000);
		$("#doc1s").hide();
		$("#doc2s").hide();
		$("#doc3s").hide();
		$("#doc4s").hide();
		$("#doc5s").hide();
		$("#doc6s").hide();
		$("#doc7s").hide();
		$("#doc9s").hide();
		$("#doc10s").hide();
		$("#doc11s").hide();
		$("#doc12s").hide();
		$("#doc13s").hide();
		document.getElementById("after0").innerHTML ="";
		document.getElementById("after").innerHTML ="";
		document.getElementById("after2").innerHTML ="";
		document.getElementById("after3").innerHTML ="";
		document.getElementById("after4").innerHTML ="";
		document.getElementById("after5").innerHTML ="";
		document.getElementById("after6").innerHTML ="";
		document.getElementById("after7").innerHTML ="";
		document.getElementById("after9").innerHTML ="";
		document.getElementById("after10").innerHTML ="";
		document.getElementById("after11").innerHTML ="";
		document.getElementById("after12").innerHTML ="";
		document.getElementById("after13").innerHTML ="";
	}else if (cotizacións.value==9){
		document.getElementById("after9").innerHTML ="Ver ejemplo 9";
		$("#doc9s").slideDown(2000);
		$("#doc1s").hide();
		$("#doc2s").hide();
		$("#doc3s").hide();
		$("#doc4s").hide();
		$("#doc5s").hide();
		$("#doc6s").hide();
		$("#doc7s").hide();
		$("#doc8s").hide();
		$("#doc10s").hide();
		$("#doc11s").hide();
		$("#doc12s").hide();
		$("#doc13s").hide();
		document.getElementById("after0").innerHTML ="";
		document.getElementById("after").innerHTML ="";
		document.getElementById("after2").innerHTML ="";
		document.getElementById("after3").innerHTML ="";
		document.getElementById("after4").innerHTML ="";
		document.getElementById("after5").innerHTML ="";
		document.getElementById("after6").innerHTML ="";
		document.getElementById("after7").innerHTML ="";
		document.getElementById("after8").innerHTML ="";
		document.getElementById("after10").innerHTML ="";
		document.getElementById("after11").innerHTML ="";
		document.getElementById("after12").innerHTML ="";
		document.getElementById("after13").innerHTML ="";
	}else if (cotizacións.value==10){
		document.getElementById("after10").innerHTML ="Ver ejemplo 10";
		$("#doc10s").slideDown(2000);
		$("#doc1s").hide();
		$("#doc2s").hide();
		$("#doc3s").hide();
		$("#doc4s").hide();
		$("#doc5s").hide();
		$("#doc6s").hide();
		$("#doc7s").hide();
		$("#doc8s").hide();
		$("#doc9s").hide();
		$("#doc11s").hide();
		$("#doc12s").hide();
		$("#doc13s").hide();
		document.getElementById("after0").innerHTML ="";
		document.getElementById("after").innerHTML ="";
		document.getElementById("after2").innerHTML ="";
		document.getElementById("after3").innerHTML ="";
		document.getElementById("after4").innerHTML ="";
		document.getElementById("after5").innerHTML ="";
		document.getElementById("after6").innerHTML ="";
		document.getElementById("after7").innerHTML ="";
		document.getElementById("after8").innerHTML ="";
		document.getElementById("after9").innerHTML ="";
		document.getElementById("after11").innerHTML ="";
		document.getElementById("after12").innerHTML ="";
		document.getElementById("after13").innerHTML ="";
	}else if (cotizacións.value==11){
		document.getElementById("after11").innerHTML ="Ver ejemplo 11";
		$("#doc11s").slideDown(2000);
		$("#doc1s").hide();
		$("#doc2s").hide();
		$("#doc3s").hide();
		$("#doc4s").hide();
		$("#doc5s").hide();
		$("#doc6s").hide();
		$("#doc7s").hide();
		$("#doc8s").hide();
		$("#doc9s").hide();
		$("#doc10s").hide();
		$("#doc12s").hide();
		$("#doc13s").hide();
		document.getElementById("after0").innerHTML ="";
		document.getElementById("after").innerHTML ="";
		document.getElementById("after2").innerHTML ="";
		document.getElementById("after3").innerHTML ="";
		document.getElementById("after4").innerHTML ="";
		document.getElementById("after5").innerHTML ="";
		document.getElementById("after6").innerHTML ="";
		document.getElementById("after7").innerHTML ="";
		document.getElementById("after8").innerHTML ="";
		document.getElementById("after9").innerHTML ="";
		document.getElementById("after10").innerHTML ="";
		document.getElementById("after12").innerHTML ="";
		document.getElementById("after13").innerHTML ="";
	}else if (cotizacións.value==12){
		document.getElementById("after12").innerHTML ="Ver ejemplo 12";
		$("#doc12s").slideDown(2000);
		$("#doc1s").hide();
		$("#doc2s").hide();
		$("#doc3s").hide();
		$("#doc4s").hide();
		$("#doc5s").hide();
		$("#doc6s").hide();
		$("#doc7s").hide();
		$("#doc8s").hide();
		$("#doc9s").hide();
		$("#doc10s").hide();
		$("#doc11s").hide();
		$("#doc13s").hide();
		document.getElementById("after0").innerHTML ="";
		document.getElementById("after").innerHTML ="";
		document.getElementById("after2").innerHTML ="";
		document.getElementById("after3").innerHTML ="";
		document.getElementById("after4").innerHTML ="";
		document.getElementById("after5").innerHTML ="";
		document.getElementById("after6").innerHTML ="";
		document.getElementById("after7").innerHTML ="";
		document.getElementById("after8").innerHTML ="";
		document.getElementById("after9").innerHTML ="";
		document.getElementById("after10").innerHTML ="";
		document.getElementById("after11").innerHTML ="";
		document.getElementById("after13").innerHTML ="";
	}else if (cotizacións.value==13){
		document.getElementById("after13").innerHTML ="Ver ejemplo 13";
		$("#doc13s").slideDown(2000);
		$("#doc1s").hide();
		$("#doc2s").hide();
		$("#doc3s").hide();
		$("#doc4s").hide();
		$("#doc5s").hide();
		$("#doc6s").hide();
		$("#doc7s").hide();
		$("#doc8s").hide();
		$("#doc9s").hide();
		$("#doc10s").hide();
		$("#doc11s").hide();
		$("#doc12s").hide();
		document.getElementById("after0").innerHTML ="";
		document.getElementById("after").innerHTML ="";
		document.getElementById("after2").innerHTML ="";
		document.getElementById("after3").innerHTML ="";
		document.getElementById("after4").innerHTML ="";
		document.getElementById("after5").innerHTML ="";
		document.getElementById("after6").innerHTML ="";
		document.getElementById("after7").innerHTML ="";
		document.getElementById("after8").innerHTML ="";
		document.getElementById("after9").innerHTML ="";
		document.getElementById("after10").innerHTML ="";
		document.getElementById("after11").innerHTML ="";
		document.getElementById("after12").innerHTML ="";
	}else if (cotizacións.value==0){
		document.getElementById("after0").innerHTML ="ERROR por favor seleccione una opción de abajo";
		$("#doc1s").hide();
		$("#doc2s").hide();
		$("#doc3s").hide();
		$("#doc4s").hide();
		$("#doc5s").hide();
		$("#doc6s").hide();
		$("#doc7s").hide();
		$("#doc8s").hide();
		$("#doc9s").hide();
		$("#doc10s").hide();
		$("#doc11s").hide();
		$("#doc12s").hide();
		$("#doc13s").hide();
		document.getElementById("after").innerHTML ="";
		document.getElementById("after2").innerHTML ="";
		document.getElementById("after3").innerHTML ="";
		document.getElementById("after4").innerHTML ="";
		document.getElementById("after5").innerHTML ="";
		document.getElementById("after6").innerHTML ="";
		document.getElementById("after7").innerHTML ="";
		document.getElementById("after8").innerHTML ="";
		document.getElementById("after9").innerHTML ="";
		document.getElementById("after10").innerHTML ="";
		document.getElementById("after11").innerHTML ="";
		document.getElementById("after12").innerHTML ="";
		document.getElementById("after13").innerHTML ="";
	}else{
		document.getElementById("after").innerHTML ="";
		document.getElementById("after2").innerHTML ="";
		document.getElementById("after3").innerHTML ="";
		document.getElementById("after4").innerHTML ="";
		document.getElementById("after5").innerHTML ="";
		document.getElementById("after6").innerHTML ="";
		document.getElementById("after7").innerHTML ="";
		document.getElementById("after8").innerHTML ="";
		document.getElementById("after9").innerHTML ="";
		document.getElementById("after10").innerHTML ="";
		document.getElementById("after11").innerHTML ="";
		document.getElementById("after12").innerHTML ="";
		document.getElementById("after13").innerHTML ="";
		
	} 
		
	}